import { consts } from './utils/constants'
import { bnArg, expect, getSigners } from './utils/helpers'
import BN from 'bn.js'
import { ApiPromise } from '@polkadot/api'
import oracleConstructor from '../../typechain-generated/constructors/oracle'
import oracleContract from '../../typechain-generated/contracts/oracle'
import rewardConstructor from '../../typechain-generated/constructors/reward'
import rewardContract from '../../typechain-generated/contracts/reward'
import poolConstructor from '../../typechain-generated/constructors/pool'
import poolContract from '../../typechain-generated/contracts/pool'
import { IdBuilder } from '../../typechain-generated/types-arguments/pool'

